services:
  umami:
    container_name: umami  # 指定容器名称
    image: umami:latest  # 使用本地构建的镜像
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      GEO_DATABASE_URL: https://cnb.cool/flyinbug/GeoLite.mmdb/-/releases/latest/download/GeoLite2-City.mmdb
    restart: always